
wakeup:
  engine: porcupine
  provider:
    porcupine:
      accessKey: ''

# 声音设备编号
audio_device_index: -1

tts:
  engine: Edge
  provider:
    xunfei:
      appKey: ''
      secretId: ''
      secretKey: ''
asr:
  engine: Tencent
  provider:
    tencent:
      secretId: ''
      secretKey: ''
nlu:
  engine: Dialogflow
  provider:
    dialogflow:
      projectId: ''
      credentialsPath: ''
  
plugins:
  weather:
    enable: true
    key: ''
    location: 'langfang'
    patterns:
  local_music:
    enable: true
    path: ''
